#!/bin/bash


###Installation d'un WordPress viergeI
#Installation des paquets neccessaires à WordPress et à l'installation et la configuration d'un serveur LAMP
apt install ca-certificates apt-transport-https -y
apt install gnupg gnupg1 gnupg2 -y
apt install ftp -y
apt install lftp
wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add -
apt-get update && apt-get upgrade -y
apt install php7.3 php7.3-mysql php7.3-gd php7.3-curl apache2 libapache2-mod-php7.3 mariadb-server -y



#mysql -sfu root < "mysql_secure_installation.sql"
#Configuration minimale du serveur SQL
printf "0000\n n\n n\n n\n y\n y\n y\n" | mysql_secure_installation
mysql -h localhost -u root -p0000 -e "CREATE DATABASE db_wp";
mysql -h localhost -u root -p0000 -e "CREATE USER 'dbadminwp'@'localhost' IDENTIFIED BY 'Ocp6@wordpress'";
mysql -h localhost -u root -p0000 -e  "GRANT ALL PRIVILEGES ON db_wp.* TO dbadminwp@localhost";
mysql -h localhost -u root -p0000 -e "FLUSH PRIVILEGES";
mysql -h localhost -u root -p0000 -e "QUIT";

#Installation de l'application WordPress
cd /tmp && wget https://fr.wordpress.org/latest-fr_FR.zip
apt-get install unzip -y && unzip latest-fr_FR.zip
rm /var/www/html/index.html && mv wordpress/* /var/www/html/ && chown -R www-data:www-data /var/www/html/
find /var/www/html/ -type f -exec chmod 644 {} \;
find /var/www/html/ -type d -exec chmod 755 {} \;

